#################################################
# 直连机安装软件及账户信息请向对应的对接交行获取#
#################################################

server:
  port: 10009

logging:
  level:
    com.github.bluecatlee.bcm: debug

# 机器id 部署多机时保证每个服务的机器id值不同
machine:
  id: 1

bcm:
  corp-no: ""  # 企业代码
  user-no: ""  # 用户号
  http:
    host: 127.0.0.1
    port: 8899
  socket:
    enabled: false
    host: 127.0.0.1
    port: 30010
    timeout: 5000

cib:
  cid: "1100343164"
  userid: "qw1"
  userpass: "a1111111"
  http:
    host: 192.168.10.3
    port: 8007



